spring:
  application:
    name: web-management
  datasource:
    url: jdbc:mysql://localhost:3306/deptmanager_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "080403"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB



mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.jdbcTransactionManager: DEBUG

